;Aliases that are required to work with dev version (unpacked, unminified) of workspace
;copy and paste these aliases into c:\Github\dev-main\Products\ThinRDP\bin64\webaliases.ini

[Alias]

; AaaS.. Update to plugin repo location
/aaas-dev/=c:\Github\plugins\aaas\
/aaas-dev/index.html=c:\Github\plugins\aaas\index.html
/aaas-build/=C:\GitHub\plugins\AaaS\dist_aaas\
/aaas-build/index.html=C:\GitHub\plugins\AaaS\dist_aaas\index.html
/mainAaaS.js=C:\GitHub\plugins\AaaS\dist_aaas\mainAaaS.js
